[package]
name = "kprm-windows"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
kprm-catalog = { path = "../kprm-catalog" }
kprm-engine = { path = "../kprm-engine" }
winreg = "0.52"
pelite = "0.10"

[target.'cfg(windows)'.dependencies]
windows = { version = "0.58", features = [
    "Win32_Storage_FileSystem",
    "Win32_Foundation",
    "Win32_System_Diagnostics_ToolHelp",
    "Win32_System_Threading",
] }
