name = 'Avast Decryptor BigBobRoss'

[[actions]]
type = 'desktop'
pattern = '(?i)^avast_decryptor_bigbobross.*\.exe$'
company_name = '(?i)^Avast'
kind = 'file'

[[actions]]
type = 'download'
pattern = '(?i)^avast_decryptor_bigbobross.*\.exe$'
company_name = '(?i)^Avast'
kind = 'file'

[[actions]]
type = 'process'
pattern = '(?i)^avast_decryptor_bigbobross.*\.exe$'
company_name = '(?i)^Avast'
force = false
