name = 'Avast Decryptor Akira'

[[actions]]
type = 'desktop'
pattern = '(?i)^avast_decryptor_akira.*\.exe$'
company_name = '(?i)^Avast'
kind = 'file'

[[actions]]
type = 'download'
pattern = '(?i)^avast_decryptor_akira.*\.exe$'
company_name = '(?i)^Avast'
kind = 'file'

[[actions]]
type = 'process'
pattern = '(?i)^avast_decryptor_akira.*\.exe$'
company_name = '(?i)^Avast'
force = false
