name = 'Bitdefender FONIX Decryptor'

[[actions]]
type = 'desktop'
pattern = '(?i)^BDFonix.*\.(exe|log)$'
company_name = '(?i)^Bitdefender'
kind = 'file'

[[actions]]
type = 'download'
pattern = '(?i)^BDFonix.*\.(exe|log)$'
company_name = '(?i)^Bitdefender'
kind = 'file'

[[actions]]
type = 'process'
pattern = '(?i)^BDFonix.*\.exe$'
company_name = '(?i)^Bitdefender'
force = false
