name = 'Bitdefender Ouroboros Decryptor'

[[actions]]
type = 'desktop'
pattern = '(?i)^BDOuroboros.*\.(exe|log)$'
company_name = '(?i)^Bitdefender'
kind = 'file'

[[actions]]
type = 'download'
pattern = '(?i)^BDOuroboros.*\.(exe|log)$'
company_name = '(?i)^Bitdefender'
kind = 'file'

[[actions]]
type = 'process'
pattern = '(?i)^BDOuroboros.*\.exe$'
company_name = '(?i)^Bitdefender'
force = false
