name = 'Emsisoft Decryptor Bart'

[[actions]]
type = 'desktop'
pattern = '(?i)^decrypt_Bart.*\.(exe|log|txt)$'
company_name = '(?i)^Emsisoft'
kind = 'file'

[[actions]]
type = 'download'
pattern = '(?i)^decrypt_Bart.*\.(exe|log|txt)$'
company_name = '(?i)^Emsisoft'
kind = 'file'

[[actions]]
type = 'process'
pattern = '(?i)^decrypt_Bart.*\.exe$'
company_name = '(?i)^Emsisoft'
force = false
