name = 'Emsisoft Decryptor Stampado'

[[actions]]
type = 'desktop'
pattern = '(?i)^decrypt_Stampado.*\.(exe|log|txt)$'
company_name = '(?i)^Emsisoft'
kind = 'file'

[[actions]]
type = 'download'
pattern = '(?i)^decrypt_Stampado.*\.(exe|log|txt)$'
company_name = '(?i)^Emsisoft'
kind = 'file'

[[actions]]
type = 'process'
pattern = '(?i)^decrypt_Stampado.*\.exe$'
company_name = '(?i)^Emsisoft'
force = false
