name = 'Emsisoft Decryptor Amnesia'

[[actions]]
type = 'desktop'
pattern = '(?i)^decrypt_Amnesia.*\.(exe|log|txt)$'
company_name = '(?i)^Emsisoft'
kind = 'file'

[[actions]]
type = 'download'
pattern = '(?i)^decrypt_Amnesia.*\.(exe|log|txt)$'
company_name = '(?i)^Emsisoft'
kind = 'file'

[[actions]]
type = 'process'
pattern = '(?i)^decrypt_Amnesia.*\.exe$'
company_name = '(?i)^Emsisoft'
force = false
