name = 'Emsisoft Decryptor NMoreira'

[[actions]]
type = 'desktop'
pattern = '(?i)^decrypt_NMoreira.*\.(exe|log|txt)$'
company_name = '(?i)^Emsisoft'
kind = 'file'

[[actions]]
type = 'download'
pattern = '(?i)^decrypt_NMoreira.*\.(exe|log|txt)$'
company_name = '(?i)^Emsisoft'
kind = 'file'

[[actions]]
type = 'process'
pattern = '(?i)^decrypt_NMoreira.*\.exe$'
company_name = '(?i)^Emsisoft'
force = false
