name = 'Emsisoft Decryptor STOP Djvu'

[[actions]]
type = 'desktop'
pattern = '(?i)^decrypt_(STOP|STOPDjvu|Djvu).*\.(exe|log|txt)$'
company_name = '(?i)^Emsisoft'
kind = 'file'

[[actions]]
type = 'download'
pattern = '(?i)^decrypt_(STOP|STOPDjvu|Djvu).*\.(exe|log|txt)$'
company_name = '(?i)^Emsisoft'
kind = 'file'

[[actions]]
type = 'process'
pattern = '(?i)^decrypt_(STOP|STOPDjvu|Djvu).*\.exe$'
company_name = '(?i)^Emsisoft'
force = false
