name = 'Emsisoft Decryptor Globe / GlobeImposter'

[[actions]]
type = 'desktop'
pattern = '(?i)^decrypt_Globe(Imposter)?.*\.(exe|log|txt)$'
company_name = '(?i)^Emsisoft'
kind = 'file'

[[actions]]
type = 'download'
pattern = '(?i)^decrypt_Globe(Imposter)?.*\.(exe|log|txt)$'
company_name = '(?i)^Emsisoft'
kind = 'file'

[[actions]]
type = 'process'
pattern = '(?i)^decrypt_Globe(Imposter)?.*\.exe$'
company_name = '(?i)^Emsisoft'
force = false
