name = 'ESET Rovnix.A Cleaner'

[[actions]]
type = 'desktop'
pattern = '(?i)^esetrovnixcleaner.*\.(exe|log|zip)$'
company_name = '(?i)^ESET'
kind = 'file'

[[actions]]
type = 'download'
pattern = '(?i)^esetrovnixcleaner.*\.(exe|log|zip)$'
company_name = '(?i)^ESET'
kind = 'file'

[[actions]]
type = 'process'
pattern = '(?i)^esetrovnixcleaner.*\.exe$'
company_name = '(?i)^ESET'
force = false
