name = 'ESET Medre Cleaner'

[[actions]]
type = 'desktop'
pattern = '(?i)^esetacadmedrecleaner.*\.(exe|log|zip)$'
company_name = '(?i)^ESET'
kind = 'file'

[[actions]]
type = 'download'
pattern = '(?i)^esetacadmedrecleaner.*\.(exe|log|zip)$'
company_name = '(?i)^ESET'
kind = 'file'

[[actions]]
type = 'process'
pattern = '(?i)^esetacadmedrecleaner.*\.exe$'
company_name = '(?i)^ESET'
force = false
