name = 'ESET Dorkbot Cleaner'

[[actions]]
type = 'desktop'
pattern = '(?i)^esetdorkbotcleaner.*\.(exe|log|zip)$'
company_name = '(?i)^ESET'
kind = 'file'

[[actions]]
type = 'download'
pattern = '(?i)^esetdorkbotcleaner.*\.(exe|log|zip)$'
company_name = '(?i)^ESET'
kind = 'file'

[[actions]]
type = 'process'
pattern = '(?i)^esetdorkbotcleaner.*\.exe$'
company_name = '(?i)^ESET'
force = false
