name = 'ESET Mabezat Decryptor'

[[actions]]
type = 'desktop'
pattern = '(?i)^esetmabezatadecryptor.*\.(exe|log)$'
company_name = '(?i)^ESET'
kind = 'file'

[[actions]]
type = 'download'
pattern = '(?i)^esetmabezatadecryptor.*\.(exe|log)$'
company_name = '(?i)^ESET'
kind = 'file'

[[actions]]
type = 'process'
pattern = '(?i)^esetmabezatadecryptor.*\.exe$'
company_name = '(?i)^ESET'
force = false
