name = 'ESET Bedep Cleaner'

[[actions]]
type = 'desktop'
pattern = '(?i)^ESETBedepCleaner.*\.(exe|log|zip)$'
company_name = '(?i)^ESET'
kind = 'file'

[[actions]]
type = 'download'
pattern = '(?i)^ESETBedepCleaner.*\.(exe|log|zip)$'
company_name = '(?i)^ESET'
kind = 'file'

[[actions]]
type = 'process'
pattern = '(?i)^ESETBedepCleaner.*\.exe$'
company_name = '(?i)^ESET'
force = false
