name = 'ESET Necurs.A Cleaner'

[[actions]]
type = 'desktop'
pattern = '(?i)^esetnecurscleaner.*\.(exe|log|zip)$'
company_name = '(?i)^ESET'
kind = 'file'

[[actions]]
type = 'download'
pattern = '(?i)^esetnecurscleaner.*\.(exe|log|zip)$'
company_name = '(?i)^ESET'
kind = 'file'

[[actions]]
type = 'process'
pattern = '(?i)^esetnecurscleaner.*\.exe$'
company_name = '(?i)^ESET'
force = false
