name = 'Kaspersky Yatron Decryptor'

[[actions]]
type = 'desktop'
pattern = '(?i)^YatronDecryptor.*\.(exe|txt|zip)'
company_name = '(?i)^Kaspersky'
kind = 'file'

[[actions]]
type = 'desktop'
pattern = '(?i)^YatronDecryptor'
kind = 'folder'

[[actions]]
type = 'download'
pattern = '(?i)^YatronDecryptor.*\.(exe|txt|zip)'
company_name = '(?i)^Kaspersky'
kind = 'file'

[[actions]]
type = 'download'
pattern = '(?i)^YatronDecryptor'
kind = 'folder'

[[actions]]
type = 'home_drive'
pattern = '(?i)^YatronDecryptor.*\.(exe|txt|zip)'
company_name = '(?i)^Kaspersky'
kind = 'file'

[[actions]]
type = 'home_drive'
pattern = '(?i)^YatronDecryptor'
kind = 'folder'
quarantine = true

[[actions]]
type = 'process'
pattern = '(?i)^YatronDecryptor.*\.exe'
company_name = '(?i)^Kaspersky'
force = false
