name = 'Kaspersky CryptXXX Decryptor'

[[actions]]
type = 'desktop'
pattern = '(?i)^(CryptXXX|Rector)Decryptor.*\.(exe|txt|zip)'
company_name = '(?i)^Kaspersky'
kind = 'file'

[[actions]]
type = 'desktop'
pattern = '(?i)^(CryptXXX|Rector)Decryptor'
kind = 'folder'

[[actions]]
type = 'download'
pattern = '(?i)^(CryptXXX|Rector)Decryptor.*\.(exe|txt|zip)'
company_name = '(?i)^Kaspersky'
kind = 'file'

[[actions]]
type = 'download'
pattern = '(?i)^(CryptXXX|Rector)Decryptor'
kind = 'folder'

[[actions]]
type = 'home_drive'
pattern = '(?i)^(CryptXXX|Rector)Decryptor.*\.(exe|txt|zip)'
company_name = '(?i)^Kaspersky'
kind = 'file'

[[actions]]
type = 'home_drive'
pattern = '(?i)^(CryptXXX|Rector)Decryptor'
kind = 'folder'
quarantine = true

[[actions]]
type = 'process'
pattern = '(?i)^(CryptXXX|Rector)Decryptor.*\.exe'
company_name = '(?i)^Kaspersky'
force = false
