name = 'ListParts'

[[actions]]
type = 'desktop'
pattern = '(?i)^listParts.*\.exe$'
company_name = '(?i)^Farbar'
kind = 'file'

[[actions]]
type = 'desktop'
pattern = '(?i)^Results\.txt$'
kind = 'file'

[[actions]]
type = 'download'
pattern = '(?i)^listParts.*\.exe$'
company_name = '(?i)^Farbar'
kind = 'file'

[[actions]]
type = 'download'
pattern = '(?i)^Results\.txt$'
kind = 'file'

[[actions]]
type = 'process'
pattern = '(?i)^listParts.*\.exe$'
company_name = '(?i)^Farbar'
force = false
