name = 'PyLocky Decryptor'

[[actions]]
type = 'desktop'
pattern = '(?i)^(PyLocky|pylocky).*\.(exe|py|log|txt|zip)$'
kind = 'file'

[[actions]]
type = 'download'
pattern = '(?i)^(PyLocky|pylocky).*\.(exe|py|log|txt|zip)$'
kind = 'file'

[[actions]]
type = 'process'
pattern = '(?i)^(PyLocky|pylocky).*\.exe$'
force = false
