name = 'ESET Crysis Decryptor'

[[actions]]
type = 'desktop'
pattern = '(?i)^esetcrysisdecryptor.*\.(exe|log)$'
company_name = '(?i)^ESET'
kind = 'file'

[[actions]]
type = 'download'
pattern = '(?i)^esetcrysisdecryptor.*\.(exe|log)$'
company_name = '(?i)^ESET'
kind = 'file'

[[actions]]
type = 'process'
pattern = '(?i)^esetcrysisdecryptor.*\.exe$'
company_name = '(?i)^ESET'
force = false
