name = 'ESET Simda Cleaner'

[[actions]]
type = 'desktop'
pattern = '(?i)^esetsimdacleaner.*\.(exe|log|zip)$'
company_name = '(?i)^ESET'
kind = 'file'

[[actions]]
type = 'download'
pattern = '(?i)^esetsimdacleaner.*\.(exe|log|zip)$'
company_name = '(?i)^ESET'
kind = 'file'

[[actions]]
type = 'process'
pattern = '(?i)^esetsimdacleaner.*\.exe$'
company_name = '(?i)^ESET'
force = false
