name = 'ESET Spy.Zbot.ZR Cleaner'

[[actions]]
type = 'desktop'
pattern = '(?i)^ESETZBotZRCleaner.*\.(exe|log|zip)$'
company_name = '(?i)^ESET'
kind = 'file'

[[actions]]
type = 'download'
pattern = '(?i)^ESETZBotZRCleaner.*\.(exe|log|zip)$'
company_name = '(?i)^ESET'
kind = 'file'

[[actions]]
type = 'process'
pattern = '(?i)^ESETZBotZRCleaner.*\.exe$'
company_name = '(?i)^ESET'
force = false
