name = 'RegtoolExport'

[[actions]]
type = 'desktop'
pattern = '(?i)^regtoolexport.*\.exe$'
kind = 'file'

[[actions]]
type = 'desktop'
pattern = '(?i)^Export.*\.reg$'
kind = 'file'

[[actions]]
type = 'download'
pattern = '(?i)^regtoolexport.*\.exe$'
kind = 'file'

[[actions]]
type = 'download'
pattern = '(?i)^Export.*\.reg$'
kind = 'file'

[[actions]]
type = 'process'
pattern = '(?i)^regtoolexport.*\.exe$'
force = false
