#include-once
#include <ButtonConstants.au3>
#include <GUIConstantsEx.au3>
#include <StaticConstants.au3>
#include <StringConstants.au3>
#include <WindowsConstants.au3>
#include <MsgBoxConstants.au3>
#include <AutoItConstants.au3>
#include <FileConstants.au3>
#include <GuiListView.au3>
#include <GuiTab.au3>
#include <Date.au3>
#include <WinAPI.au3>
#include <WinAPIProc.au3>
#include <WinAPIShellEx.au3>
#include <WinAPIFiles.au3>
#include <WinAPIEx.au3>
#include <SendMessage.au3>
#include <Array.au3>
#include <File.au3>
#include "UAC.au3"
#include "Permissions.au3"
#include "_XMLDomWrapper.au3"
#include "taskplanerCOM.au3"
#include "kp_languages.au3"
#include "actions_restart.au3"
#include "utils.au3"
#include "progress_bar.au3"
#include "restore_points.au3"
#include "registry_slow.au3"
#include "registry.au3"
#include "restore_uac.au3"
#include "restore_system_settings.au3"
#include "tools_remove.au3"
#include "tools_import.au3"
#include "delete_later.au3"
#include "custom_search.au3"
#include "variables.au3"
#include "functions.au3"