#include-once
#include <ButtonConstants.au3>
#include <GUIConstantsEx.au3>
#include <StaticConstants.au3>
#include <StringConstants.au3>
#include <WindowsConstants.au3>
#include <APIFilesConstants.au3>
#include <MsgBoxConstants.au3>
#include <AutoItConstants.au3>
#include <FileConstants.au3>
#include <GuiListView.au3>
#include <Constants.au3>
#include <GuiTab.au3>
#include <Date.au3>
#include <WinAPI.au3>
#include <WinAPIProc.au3>
#include <WinAPIShellEx.au3>
#include <WinAPIFiles.au3>
#include <WinAPIEx.au3>
#include <SendMessage.au3>
#include <Array.au3>
#include <File.au3>
#include "libs\permissions.au3"
#include "libs\xml_dom_wrapper.au3"
#include "libs\taskplaner_com.au3"
#include "libs\ext_msg_box.au3"
#include "libs\jsmn.au3"
#include "kp_languages.au3"
#include "variables.au3"
#include "functions\utils.au3"
#include "functions\style.au3"
#include "functions\progress_bar.au3"
#include "functions\backup.au3"
#include "functions\system_settings.au3"
#include "functions\uac.au3"
#include "functions\system_restore.au3"
#include "functions\remove.au3"
#include "functions\search.au3"
#include "functions\quarantines.au3"
#include "functions\functions.au3"
