Func Lang_FR()
	Global $lDeleteTools = "Supprimer les outils"
	Global $lDeleteSystemRestorePoints = "Supprimer les points de restaurations"
	Global $lCreateRestorePoint = "Créer un point de restauration"
	Global $lSaveRegistry = "Sauvegarder le registre"
	Global $lRestoreUAC = "Restaurer UAC"
	Global $lRestoreSettings = "Restaurer les paramètres système"
	Global $lRun = "Exécuter"
	Global $lFinish = "Toutes les opérations sont terminées"
	Global $lFail = "Échec"
	Global $lRegistryBackupError = "Impossible de créer une sauvegarde du registre"
	Global $lAdminRequired = "Vous devez exécuter le programme avec les droits administrateurs"
	Global $lGetLastVersionTitle = "Mise à jour"
	Global $lGetLastVersion = "Une version plus récente de KpRm existe, merci de la télécharger."
	Global $lRestart = "Vous devez redémarrer votre ordinateur pour terminer certaines actions"
	Global $lRemoveQuarantine = "Supprimer les quarantaines"
	Global $lRemoveNow = "Supprimer maintenant"
	Global $lRemoveQuarantineAfterNDays = "Supprimer dans 7 jours"
	Global $lAuto = "Automatique"
	Global $lCustom = "Personnalisé"
	Global $lNoElement = "Aucun"
	Global $lAll = "Tous"
	Global $lEmpty = "Vider"
	Global $lSearch = "Analyser"
	Global $lRemove = "Supprimer"
	Global $lActions = "Actions"
	Global $lNoSelected = "Aucun élément de sélectionné"
	Global $lFinishTitle = "Terminé"
	Global $lNoTool = "Aucun outil trouvé"
EndFunc   ;==>Lang_FR

Func Lang_EN()
	Global $lDeleteTools = "Delete Tools"
	Global $lDeleteSystemRestorePoints = "Delete Restore Points"
	Global $lCreateRestorePoint = "Create Restore Point"
	Global $lSaveRegistry = "Registry Backup"
	Global $lRestoreUAC = "UAC Restore"
	Global $lRestoreSettings = "Restore System Settings"
	Global $lRun = "Run"
	Global $lFinish = "All operations are completed"
	Global $lFail = "Fail"
	Global $lRegistryBackupError = "Unable to create a registry backup"
	Global $lAdminRequired = "You must run the program with administrator rights"
	Global $lGetLastVersionTitle = "Update"
	Global $lGetLastVersion = "A more recent version of KpRm exists, please download it!"
	Global $lRestart = "You must restart your computer to complete certain actions"
	Global $lRemoveQuarantine = "Delete quarantines"
	Global $lRemoveNow = "Delete now"
	Global $lRemoveQuarantineAfterNDays = "Delete in 7 days"
	Global $lAuto = "Automatic"
	Global $lCustom = "Customized"
	Global $lNoElement = "None"
	Global $lAll = "All"
	Global $lEmpty = "Empty"
	Global $lSearch = "Analyze"
	Global $lRemove = "Delete"
	Global $lActions = "Actions"
	Global $lNoSelected = "No selected element"
	Global $lFinishTitle = "Completed"
	Global $lNoTool = "No tools found"
EndFunc   ;==>Lang_EN

Func Lang_DE()
	Global $lDeleteTools = "Werkzeuge löschen"
	Global $lDeleteSystemRestorePoints = "Wiederherstellungspunkte löschen"
	Global $lCreateRestorePoint = "Erstellen eines Wiederherstellungspunktes"
	Global $lSaveRegistry = "Speichern der Registrierung"
	Global $lRestoreUAC = "UAC wiederherstellen"
	Global $lRestoreSettings = "Systemeinstellungen wiederherstellen"
	Global $lRun = "Ausführen"
	Global $lFinish = "Alle Vorgänge sind abgeschlossen"
	Global $lFail = "Ausfall"
	Global $lRegistryBackupError = "Es ist nicht möglich, ein Registrierungs-Backup zu erstellen"
	Global $lAdminRequired = "Sie müssen das Programm mit Administratorrechten ausführen"
	Global $lGetLastVersionTitle = "Update"
	Global $lGetLastVersion = "Es gibt eine neuere Version von KpRm, bitte laden Sie sie herunter."
	Global $lRestart = "Sie müssen Ihren Computer neu starten, um bestimmte Aktionen durchzuführen."
	Global $lRemoveQuarantine = "Quarantäne löschen"
	Global $lRemoveNow = "Jetzt löschen"
	Global $lRemoveQuarantineAfterNDays = "Löschen in 7 Tagen"
	Global $lAuto = "Automatisch"
	Global $lCustom = "Personalisiert"
	Global $lNoElement = "Keine"
	Global $lAll = "Alle"
	Global $lEmpty = "Leer"
	Global $lSearch = "Analysieren"
	Global $lRemove = "Löschen"
	Global $lActions = "Aktionen"
	Global $lNoSelected = "Kein ausgewähltes Element"
	Global $lFinishTitle = "Abgeschlossen"
	Global $lNoTool = "Keine Werkzeuge gefunden"
EndFunc   ;==>Lang_DE

Func Lang_IT()
	Global $lDeleteTools = "Cancella strumenti"
	Global $lDeleteSystemRestorePoints = "Elimina punti di ripristino"
	Global $lCreateRestorePoint = "Crea un punto di ripristino"
	Global $lSaveRegistry = "Salva registro"
	Global $lRestoreUAC = "Ripristina UAC"
	Global $lRestoreSettings = "Ripristina impostazioni di sistema"
	Global $lRun = "Eseguire"
	Global $lFinish = "Tutte le operazioni sono completate"
	Global $lFail = "Fallimento"
	Global $lRegistryBackupError = "Impossibile creare un backup del registro di sistema"
	Global $lAdminRequired = "È necessario eseguire il programma con i diritti di amministratore"
	Global $lGetLastVersionTitle = "Aggiorna"
	Global $lGetLastVersion = "Esiste una versione più recente di KpRm, scaricatela, per favore"
	Global $lRestart = "È necessario riavviare il computer per completare determinate azioni"
	Global $lRemoveQuarantine = "Cancellare le quarantene"
	Global $lRemoveNow = "Cancella ora"
	Global $lRemoveQuarantineAfterNDays = "Cancella in 7 giorni"
	Global $lAuto = "Automatico"
	Global $lCustom = "Personalizzati"
	Global $lNoElement = "Nessuna"
	Global $lAll = "Tutti"
	Global $lEmpty = "Vuoto"
	Global $lSearch = "Analizzare"
	Global $lRemove = "Cancellare"
	Global $lActions = "Azioni"
	Global $lNoSelected = "Nessun elemento selezionato"
	Global $lFinishTitle = "Completato"
	Global $lNoTool = "Nessun utensile trovato"
EndFunc   ;==>Lang_IT

Func Lang_PT()
	Global $lDeleteTools = "Apagar ferramentas"
	Global $lDeleteSystemRestorePoints = "Deletar pontos de restauração"
	Global $lCreateRestorePoint = "Criar um ponto de restauração"
	Global $lSaveRegistry = "Salvar registro"
	Global $lRestoreUAC = "Restaurar UAC"
	Global $lRestoreSettings = "Restaurar configurações do sistema"
	Global $lRun = "Executar"
	Global $lFinish = "Todas as operações estão concluídas"
	Global $lFail = "Falha"
	Global $lRegistryBackupError = "Incapaz de criar um backup do registro"
	Global $lAdminRequired = "Você deve executar o programa com direitos de administrador"
	Global $lGetLastVersionTitle = "Atualizar"
	Global $lGetLastVersion = "Uma nova versão do KpRm existe, por favor faça o download."
	Global $lRestart = "Você deve reiniciar seu computador para concluir certas ações"
	Global $lRemoveQuarantine = "Eliminar quarentenas"
	Global $lRemoveNow = "Eliminar agora"
	Global $lRemoveQuarantineAfterNDays = "Eliminar em 7 dias"
	Global $lAuto = "Automático"
	Global $lCustom = "Personalizado"
	Global $lNoElement = "Nenhuma"
	Global $lAll = "Todos"
	Global $lEmpty = "Vazio"
	Global $lSearch = "Analisar"
	Global $lRemove = "Eliminar"
	Global $lActions = "Ações"
	Global $lNoSelected = "Nenhum item marcado"
	Global $lFinishTitle = "Concluído"
	Global $lNoTool = "Nenhuma ferramenta encontrada"
EndFunc   ;==>Lang_PT

Func Lang_RU()
	Global $lDeleteTools = "Инструменты удаления"
	Global $lDeleteSystemRestorePoints = "Удалить точки восстановления"
	Global $lCreateRestorePoint = "Создать точку восстановления"
	Global $lSaveRegistry = "Резервное копирование реестра"
	Global $lRestoreUAC = "Восстановление UAC"
	Global $lRestoreSettings = "Восстановить настройки системы"
	Global $lRun = "Запустить"
	Global $lFinish = "Все операции завершены"
	Global $lFail = "Ошибка"
	Global $lRegistryBackupError = "Не удается создать резервную копию реестра"
	Global $lAdminRequired = "Вы должны запустить программу от имени администратора"
	Global $lGetLastVersionTitle = "Обновление"
	Global $lGetLastVersion = "Существует более свежая версия KpRm, пожалуйста, скачайте её!"
	Global $lRestart = "Для выполнения определенных действий необходимо перезагрузить компьютер."
	Global $lRemoveQuarantine = "Удалить карантин"
	Global $lRemoveNow = "Удалить"
	Global $lRemoveQuarantineAfterNDays = "Удалить через 7 дней"
	Global $lAuto = "Автоматический"
	Global $lCustom = "Персонализированный"
	Global $lNoElement = "Нет"
	Global $lAll = "Все они"
	Global $lEmpty = "Пусто"
	Global $lSearch = "Анализировать"
	Global $lRemove = "Удалить"
	Global $lActions = "Действия"
	Global $lNoSelected = "Нет выбранных элементов"
	Global $lFinishTitle = "Завершено"
	Global $lNoTool = "Инструментов не найдено"
EndFunc   ;==>Lang_RU

Func Lang_ES()
	Global $lDeleteTools = "Borrar herramientas"
	Global $lDeleteSystemRestorePoints = "Eliminar puntos de restauración"
	Global $lCreateRestorePoint = "Crear un punto de restauración"
	Global $lSaveRegistry = "Guardar el registro"
	Global $lRestoreUAC = "Restaurar UAC"
	Global $lRestoreSettings = "Restaurar ajustes del sistema"
	Global $lRun = "Ejecutar"
	Global $lFinish = "Todas las operaciones están terminadas"
	Global $lFail = "fallo"
	Global $lRegistryBackupError = "Incapaz de crear una copia de seguridad del registro"
	Global $lAdminRequired = "Debe ejecutar el programa con derechos de administrador"
	Global $lGetLastVersionTitle = "Actualización"
	Global $lGetLastVersion = "Existe una nueva versión de KpRm, por favor descárguela."
	Global $lRestart = "Debe reiniciar el equipo para completar ciertas acciones"
	Global $lRemoveQuarantine = "Borrar cuarentenas"
	Global $lRemoveNow = "Borrar ahora"
	Global $lRemoveQuarantineAfterNDays = "Borrar en 7 días"
	Global $lAuto = "Automático"
	Global $lCustom = "Personalizado"
	Global $lNoElement = "Ninguno"
	Global $lAll = "Todos"
	Global $lEmpty = "Vacío"
	Global $lSearch = "Analizar"
	Global $lRemove = "Borrar"
	Global $lActions = "Acciones"
	Global $lNoSelected = "Ninguna posición fija"
	Global $lFinishTitle = "Concluido"
	Global $lNoTool = "No se han encontrado herramientas"
EndFunc   ;==>Lang_ES

Func Lang_NL()
	Global $lDeleteTools = "Gereedschap verwijderen"
	Global $lDeleteSystemRestorePoints = "Restauratiepunten verwijderen"
	Global $lCreateRestorePoint = "Creëer een herstelpunt"
	Global $lSaveRegistry = "Sla het register op"
	Global $lRestoreUAC = "UAC herstellen"
	Global $lRestoreSettings = "Systeeminstellingen herstellen"
	Global $lRun = "Uitvoeren"
	Global $lFinish = "Alle bewerkingen zijn voltooid"
	Global $lFail = "Falen"
	Global $lRegistryBackupError = "Niet in staat om een back-up van het register te maken"
	Global $lAdminRequired = "U moet het programma met beheerdersrechten uitvoeren."
	Global $lGetLastVersionTitle = "Update"
	Global $lGetLastVersion = "Een recentere versie van KpRm bestaat, download deze alsjeblieft."
	Global $lRestart = "U moet uw computer opnieuw opstarten om bepaalde acties te voltooien"
	Global $lRemoveQuarantine = "Quarantaines verwijderen"
	Global $lRemoveNow = "Nu verwijderen"
	Global $lRemoveQuarantineAfterNDays = "Verwijderen in 7 dagen"
	Global $lAuto = "Automatisch"
	Global $lCustom = "Gepersonaliseerd"
	Global $lNoElement = "Geen"
	Global $lAll = "Allemaal"
	Global $lEmpty = "Leeg"
	Global $lSearch = "Analyseren"
	Global $lRemove = "Verwijderen"
	Global $lActions = "Acties"
	Global $lNoSelected = "Geen geselecteerde artikele"
	Global $lFinishTitle = "Voltooid"
	Global $lNoTool = "Geen gereedschap gevonden"
EndFunc   ;==>Lang_NL

Select
	Case StringRegExp(@OSLang, "..0C$")
		Lang_FR()
	Case StringRegExp(@OSLang, "..10$")
		Lang_IT()
	Case StringRegExp(@OSLang, "..07$")
		Lang_DE()
	Case StringRegExp(@OSLang, "..0A$")
		Lang_ES()
	Case StringRegExp(@OSLang, "..16$")
		Lang_PT()
	Case StringRegExp(@OSLang, "..13$")
		Lang_NL()
	Case StringRegExp(@OSLang, "..19$")
		Lang_RU()
	Case Else
		Lang_EN()
EndSelect
